import React from 'react'
import Image from 'next/image'
import devProfile from '../public/devprofile1.png'
import StepCard from '../components/StepCard'

const steps = [
	{
		step: "Signup with Linkedln",
		description: "So you don't need to write about yourself again.",
	},
	{
		step: "Download devProfiler",
		description: "Download dev-profiler executable and run it on your local machine. It will find your local git repositories and generate a report of your contributions completely offline.",
	},
	{
		step: "Get your devProfile",
		description: "Upload the report generated by dev-profiler to claim your devProfile.",
	}
]
const Steps = () => {
	return (
		<div id='steps' className='h-[120%] mb-12'>
			<h2 className='font-bold text-[2rem] text-center'>Just <span className='sm:text-[60px] text-[40px] text-primary-main'>3</span> steps for <span className='text-[2rem] text-primary-main font-bold'>devProfile</span></h2>
			<div className='sm:flex justify-center p-10'>
				<div className='p-3 w-[65%] mr-3'>
					{
						steps.map((item, index) => {
							return <StepCard key={index} step={item.step} description={item.description} />
						})
					}
				</div>
				<div>
					<Image src={devProfile} className="border-2 drop-shadow-md rounded-md md:block hidden" alt='devProfile image' />
				</div>
			</div>
		</div>
	)
}

export default Steps